[project]
name = "mydigitaltwin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests",
    "python-dotenv",
    "gradio",
    "pypdf",
    "openai",
    "openai-agents",
    "beautifulsoup4"
]